export const bibleMetadata: {
  [abrev: string]: {
    chapters: number,
    normal: string,
    gringo: string
  }
} = {
  "gn": { chapters: 50, normal: 'Genesis', gringo: 'Genesis' },
  "ex": { chapters: 40, normal: 'Exodo', gringo: 'Exodus' },
  "lv": { chapters: 27, normal: 'Levitico', gringo: 'Leviticus' },
  "nm": { chapters: 36, normal: 'Numeros', gringo: 'Numbers' },
  "dt": { chapters: 34, normal: 'Deuteronomio', gringo: 'Deuteronomy' },
  "js": { chapters: 24, normal: 'Josue', gringo: 'Joshua' },
  "jz": { chapters: 21, normal: 'Juizes', gringo: 'Judges' },
  "rt": { chapters: 4, normal: 'Rute', gringo: 'Ruth' },
  "1sm": { chapters: 31, normal: '1Samuel', gringo: '1 Samuel' },
  "2sm": { chapters: 24, normal: '2Samuel', gringo: '2 Samuel' },
  "1rs": { chapters: 22, normal: '1Reis', gringo: '1 Kings' },
  "2rs": { chapters: 25, normal: '2Reis', gringo: '2 Kings' },
  "1cr": { chapters: 29, normal: '1Cronicas', gringo: '1 Chronicles' },
  "2cr": { chapters: 36, normal: '2Cronicas', gringo: '2 Chronicles' },
  "ed": { chapters: 10, normal: 'Esdras', gringo: 'Ezra' },
  "ne": { chapters: 13, normal: 'Neemias', gringo: 'Nehemiah' },
  "et": { chapters: 10, normal: 'Ester', gringo: 'Esther' },
  "jo": { chapters: 42, normal: 'Jo', gringo: 'Job' },
  "sl": { chapters: 150, normal: 'Salmos', gringo: 'Psalms' },
  "pv": { chapters: 31, normal: 'Proverbios', gringo: 'Proverbs' },
  "ec": { chapters: 12, normal: 'Eclesiastes', gringo: 'Ecclesiastes' },
  "ct": { chapters: 8, normal: 'Canticos', gringo: 'Song of Solomon' },
  "is": { chapters: 66, normal: 'Isaias', gringo: 'Isaiah' },
  "jr": { chapters: 52, normal: 'Jeremias', gringo: 'Jeremiah' },
  "lm": { chapters: 5, normal: 'Lamentacoes', gringo: 'Lamentations' },
  "ez": { chapters: 48, normal: 'Ezequiel', gringo: 'Ezekiel' },
  "dn": { chapters: 12, normal: 'Daniel', gringo: 'Daniel' },
  "os": { chapters: 14, normal: 'Oseias', gringo: 'Hosea' },
  "jl": { chapters: 3, normal: 'Joel', gringo: 'Joel' },
  "am": { chapters: 9, normal: 'Amos', gringo: 'Amos' },
  "ob": { chapters: 1, normal: 'Obadias', gringo: 'Obadiah' },
  "jn": { chapters: 4, normal: 'Jonas', gringo: 'Jonah' },
  "mq": { chapters: 7, normal: 'Miqueias', gringo: 'Micah' },
  "na": { chapters: 3, normal: 'Naum', gringo: 'Nahum' },
  "hc": { chapters: 3, normal: 'Habacuque', gringo: 'Habakkuk' },
  "sf": { chapters: 3, normal: 'Sofonias', gringo: 'Zephaniah' },
  "ag": { chapters: 2, normal: 'Ageu', gringo: 'Haggai' },
  "zc": { chapters: 14, normal: 'Zacarias', gringo: 'Zechariah' },
  "ml": { chapters: 4, normal: 'Malaquias', gringo: 'Malachi' },
  "mt": { chapters: 28, normal: 'Mateus', gringo: 'Matthew' },
  "mc": { chapters: 16, normal: 'Marcos', gringo: 'Mark' },
  "lc": { chapters: 24, normal: 'Lucas', gringo: 'Luke' },
  "joao": { chapters: 21, normal: 'Joao', gringo: 'John' },
  "atos": { chapters: 28, normal: 'Atos', gringo: 'Acts' },
  "rm": { chapters: 16, normal: 'Romanos', gringo: 'Romans' },
  "1co": { chapters: 16, normal: '1Corintios', gringo: '1 Corinthians' },
  "2co": { chapters: 13, normal: '2Corintios', gringo: '2 Corinthians' },
  "gl": { chapters: 6, normal: 'Galatas', gringo: 'Galatians' },
  "ef": { chapters: 6, normal: 'Efesios', gringo: 'Ephesians' },
  "fp": { chapters: 4, normal: 'Filipenses', gringo: 'Philippians' },
  "cl": { chapters: 4, normal: 'Colossenses', gringo: 'Colossians' },
  "1ts": { chapters: 5, normal: '1Tessalonicenses', gringo: '1 Thessalonians' },
  "2ts": { chapters: 3, normal: '2Tessalonicenses', gringo: '2 Thessalonians' },
  "1tm": { chapters: 6, normal: '1Timoteo', gringo: '1 Timothy' },
  "2tm": { chapters: 4, normal: '2Timoteo', gringo: '2 Timothy' },
  "tt": { chapters: 3, normal: 'Tito', gringo: 'Titus' },
  "fm": { chapters: 1, normal: 'Filemom', gringo: 'Philemon' },
  "hb": { chapters: 13, normal: 'Hebreus', gringo: 'Hebrews' },
  "tg": { chapters: 5, normal: 'Tiago', gringo: 'James' },
  "1pe": { chapters: 5, normal: '1Pedro', gringo: '1 Peter' },
  "2pe": { chapters: 3, normal: '2Pedro', gringo: '2 Peter' },
  "1jo": { chapters: 5, normal: '1Joao', gringo: '1 John' },
  "2jo": { chapters: 1, normal: '2Joao', gringo: '2 John' },
  "3jo": { chapters: 1, normal: '3Joao', gringo: '3 John' },
  "jd": { chapters: 1, normal: 'Judas', gringo: 'Jude' },
  "ap": { chapters: 22, normal: 'Apocalipse', gringo: 'Revelation' }
}
