import { OldTestamentBooksUnion } from "../../domain/old-testament-books-union";

export function createOldTestmentObjectBase(): { [oldBook in OldTestamentBooksUnion]: Array<any> } {
  return {
    'GEN': [],
    'EXO': [],
    'LEV': [],
    'NUM': [],
    'DEU': [],
    'JOS': [],
    'JUI': [],
    'RUT': [],
    '1SM': [],
    '2SM': [],
    '1RS': [],
    '2RS': [],
    '1CR': [],
    '2CR': [],
    '1ED': [],
    '2ED': [],
    '1ET': [],
    'JOB': [],
    'SAL': [],
    'PRO': [],
    'ECL': [],
    'CAN': [],
    'ISA': [],
    'JE1': [],
    'JE2': [],
    'EZE': [],
    'DA1': [],
    'OSE': [],
    'JOE': [],
    'AMO': [],
    'OBA': [],
    'JON': [],
    'MIQ': [],
    'NAU': [],
    'HAB': [],
    'SOF': [],
    'AGE': [],
    'ZAC': [],
    'MAL': []
  };
}