/**
 * https://cafetorah.com/lista-de-textos-biblicos-e-apocrifos-encontrados-nos-manuscritos-do-mar-morto/
 * https://www.deadseascrolls.org.il/
 */
export enum EsseneQmranHaYahad {
  COPPER_SCROLL_3QCOPSCR,

  RULE_OF_COMMUNITY_SEREKH_HAYAHAD_QS,
  RULE_OF_WAR_SCROLL_MILHAMAH_QM,
  THANKSGIVING_HYMNS_HODAYOT_SCROLL_QH,
  PHYSIOGNOMIES_4T186,
  TEMPLE_SCROLL_QTEMPLESCROLL,
  JONATHAN_SCROLL_4T523,
  DOCUMENT_OF_DAMASCUS_QD,
  SAPIENTIAL_INSTRUCTION_1T,
  BOOK_OF_MYSTERIES_QMYST,
  MELQUISEDEQUE_QMELCH,
  SONGS_OF_THE_SABBATH_SACRIFICE_QSHIRSHABB,

  TOBIT_4QTOBIT,
  BEN_SIRA_BOOK,
  TOHOROT_SCROLL,
  BLESSING_BERAKHOT_SCROLLS_QPAPBENED,
  COURSE_SCROLLS_QCOURSE,

  JUBILEES_QJUB,
  ENOCH_QEN,
  NOAH_QNOAH,
  BOOK_OF_GIANTS_QENGIANTS,

  TESTAMENT_OF_LEVI_ANCIENT_QLEVI_QPALEOLEV,
  TESTAMENT_OF_LEVI_QLEVI,
  TESTAMENT_OF_NAPHTALI_QTNAPH,
  TESTAMENT_OF_JUDAH,
  TESTAMENT_OF_JOSEPH_TJOSEPH,
  TESTAMENT_OF_QAHAT_4QTKOHATH,

  FORGOTTEN_GENESIS_QAPGEN,
  FORGOTTEN_JOSHUA_4QAPOCRJOSH,
  FORGOTTEN_KINGS_PAP6QAPOCRSAMKGS,
  FORGOTTEN_PSALMS,
  FORGOTTEN_DANIEL_4Q246,
  FORGOTTEN_APOCALYPSE_QAPOCRDAN,
  FORGOTTEN_PROPHECIES_QAPPROPH,
  FORGOTTEN_SACERDOTAL_PROPHECIES_QAPPROPH,
  FORGOTTEN_HAMESSIAH_APOCALYPSE_4T521,
  FORGOTTEN_NEW_JERUSALEM_DESCRIPTION_QNJ,

  MISHNA_TORAH_4QMMT,
  PESHER_GENESIS_SCROLL_QCOMMGEN,
  PESHER_ISAIAH_SCROLL_QPISA,
  PESHER_MICAH_SCROLL_QPMIC,
  PESHER_ZEPHANIAH_SCROLL_QPZEPH,
  PESHER_HABAKKUK_SCROLL_QPHAB,
  PESHER_PSALMS_SCROLL_QPPS,
  PESHER_APOCALYPSE_OF_WEEKS_4Q247
}
