/**
 * https://www.ethiopianorthodox.org/
 */
export enum TawahedoBook {
  OLD_JUBLEE = 'OLD_JUBLEE',
  OLD_ENOCH = 'OLD_ENOCH',
  OLD_BEL_AND_DRAGON = 'OLD_BEL_AND_DRAGON',
  OLD_EZRA2 = 'OLD_EZRA2',
  OLD_EZRA_SUTUEL = 'OLD_EZRA_SUTUEL',
  OLD_TOBIT = 'OLD_TOBIT',
  OLD_JUDITH = 'OLD_JUDITH',
  OLD_MACCABEES1 = 'OLD_MACCABEES1',
  OLD_MACCABEES2 = 'OLD_MACCABEES2',
  OLD_MACCABEES3 = 'OLD_MACCABEES3',
  OLD_TEGSATS = 'OLD_TEGSATS',
  OLD_METSIHAFE_TIBEB = 'OLD_METSIHAFE_TIBEB',
  OLD_JOSHUA_SON_OF_SIRAC = 'OLD_JOSHUA_SON_OF_SIRAC',
  OLD_JOSEPHAS_SON_OF_BENGORION = 'OLD_JOSEPHAS_SON_OF_BENGORION',
  NEW_SIRATE = 'NEW_SIRATE',
  NEW_TIZAZ = 'NEW_TIZAZ',
  NEW_GITSEW = 'NEW_GITSEW',
  NEW_ABTILIS = 'NEW_ABTILIS',
  NEW_DOMINOS1 = 'NEW_DOMINOS1',
  NEW_DOMINOS2 = 'NEW_DOMINOS2',
  NEW_CLEMENT = 'NEW_CLEMENT',
  NEW_DIDASCALIA = 'NEW_DIDASCALIA'
}
