/**
 * TypeScript definitions for potrace-plus.
 *
 * Potrace Plus
 * https://github.com/herrstrietzel/potrace-plus
 *
 * Browser usage:
 *
 *     <script src="scripts/potrace-plus.min.js"></script>
 *
 * The browser build exposes `PotracePlus` globally.
 */


/* ========================================================================== */
/*                                GEOMETRY                                   */
/* ========================================================================== */

/**
 * A two-dimensional point.
 */
interface PotracePoint {

    /**
     * Horizontal coordinate.
     */
    x: number;

    /**
     * Vertical coordinate.
     */
    y: number;
}


/**
 * Axis-aligned bounding box.
 */
interface PotraceBoundingBox {

    /**
     * Left coordinate.
     */
    x: number;

    /**
     * Top coordinate.
     */
    y: number;

    /**
     * Width.
     */
    width: number;

    /**
     * Height.
     */
    height: number;
}


/* ========================================================================== */
/*                             SVG PATH COMMANDS                              */
/* ========================================================================== */

/**
 * SVG `moveto` command generated by Potrace.
 *
 * Potrace Plus attaches additional metadata to the initial `M`
 * command of a contour.
 */
interface PotraceMoveCommand {

    /**
     * SVG command type.
     */
    type: "M";

    /**
     * `[x, y]`
     */
    values: [number, number];

    /**
     * Bounding box of the Potrace path.
     */
    bb?: PotraceBoundingBox;

    /**
     * Potrace path orientation.
     */
    cw?: boolean;
}


/**
 * SVG `lineto` command.
 */
interface PotraceLineCommand {

    /**
     * SVG command type.
     */
    type: "L";

    /**
     * `[x, y]`
     */
    values: [number, number];
}


/**
 * SVG cubic Bézier command.
 *
 * Values:
 *
 * `[x1, y1, x2, y2, x, y]`
 */
interface PotraceCubicBezierCommand {

    /**
     * SVG command type.
     */
    type: "C";

    /**
     * First control point, second control point and endpoint.
     */
    values: [
        number,
        number,
        number,
        number,
        number,
        number
    ];
}


/**
 * SVG close-path command.
 */
interface PotraceCloseCommand {

    /**
     * SVG command type.
     */
    type: "Z";

    /**
     * Close-path has no arguments.
     */
    values: [];
}


/**
 * Absolute SVG path command.
 */
type PotraceAbsolutePathCommand =
    | PotraceMoveCommand
    | PotraceLineCommand
    | PotraceCubicBezierCommand
    | PotraceCloseCommand;


/* ========================================================================== */
/*                         RELATIVE SVG COMMANDS                              */
/* ========================================================================== */

/**
 * Relative SVG `moveto`.
 */
interface PotraceRelativeMoveCommand {

    type: "m";

    /**
     * `[dx, dy]`
     */
    values: [number, number];

    /**
     * Bounding box of the original path.
     */
    bb?: PotraceBoundingBox;

    /**
     * Original Potrace path orientation.
     */
    cw?: boolean;
}


/**
 * Relative SVG `lineto`.
 */
interface PotraceRelativeLineCommand {

    type: "l";

    /**
     * `[dx, dy]`
     */
    values: [number, number];
}


/**
 * Relative SVG cubic Bézier.
 */
interface PotraceRelativeCubicBezierCommand {

    type: "c";

    /**
     * Relative control points and endpoint.
     */
    values: [
        number,
        number,
        number,
        number,
        number,
        number
    ];
}


/**
 * Relative SVG close-path.
 */
interface PotraceRelativeCloseCommand {

    type: "z";

    values: [];
}


/* ========================================================================== */
/*                           SVG SHORTHAND COMMANDS                           */
/* ========================================================================== */

/**
 * SVG horizontal line command.
 */
interface PotraceHorizontalLineCommand {

    type: "H" | "h";

    values: [number];
}


/**
 * SVG vertical line command.
 */
interface PotraceVerticalLineCommand {

    type: "V" | "v";

    values: [number];
}


/**
 * SVG smooth cubic Bézier command.
 */
interface PotraceSmoothCubicBezierCommand {

    type: "S" | "s";

    values: [
        number,
        number,
        number,
        number
    ];
}


/**
 * SVG quadratic Bézier command.
 */
interface PotraceQuadraticBezierCommand {

    type: "Q" | "q";

    values: [
        number,
        number,
        number,
        number
    ];
}


/**
 * SVG smooth quadratic Bézier command.
 */
interface PotraceSmoothQuadraticBezierCommand {

    type: "T" | "t";

    values: [number, number];
}


/**
 * SVG path command after optimization.
 *
 * Depending on `toRelative` and `toShorthands`, the path may contain
 * absolute commands, relative commands, or shorthand commands.
 */
type PotraceOptimizedPathCommand =
    | PotraceMoveCommand
    | PotraceLineCommand
    | PotraceCubicBezierCommand
    | PotraceCloseCommand
    | PotraceRelativeMoveCommand
    | PotraceRelativeLineCommand
    | PotraceRelativeCubicBezierCommand
    | PotraceRelativeCloseCommand
    | PotraceHorizontalLineCommand
    | PotraceVerticalLineCommand
    | PotraceSmoothCubicBezierCommand
    | PotraceQuadraticBezierCommand
    | PotraceSmoothQuadraticBezierCommand;


/**
 * Complete SVG path-data array.
 */
type PotracePathData = PotraceOptimizedPathCommand[];


/**
 * One normalized Potrace contour.
 */
type PotraceSubPath = PotraceAbsolutePathCommand[];


/**
 * Collection of normalized Potrace contours.
 */
type PotracePathDataArray = PotraceSubPath[];


/* ========================================================================== */
/*                                  POLYGON                                   */
/* ========================================================================== */

/**
 * A polygon generated from a Potrace contour.
 */
type PotracePolygon = PotracePoint[];


/**
 * Collection of Potrace polygons.
 */
type PotracePolygonArray = PotracePolygon[];


/* ========================================================================== */
/*                              POTRACE OPTIONS                               */
/* ========================================================================== */

/**
 * Potrace turn policy.
 *
 * Determines how ambiguous pixels are resolved during path
 * decomposition.
 */
type PotraceTurnPolicy =
    | "black"
    | "white"
    | "left"
    | "right"
    | "minority"
    | "majority"
    | "random";


/**
 * Configuration options accepted by PotracePlus.
 */
interface PotracePlusOptions {

    /**
     * Potrace turn policy.
     *
     * Default: `"majority"`.
     */
    turnpolicy?: PotraceTurnPolicy;

    /**
     * Suppress speckles up to this size.
     *
     * Default: `1`.
     */
    turdsize?: number;

    /**
     * Corner threshold parameter.
     *
     * Default: `1`.
     */
    alphamax?: number;

    /**
     * Enable curve optimization.
     *
     * Default: `true`.
     */
    optcurve?: boolean;

    /**
     * Curve optimization tolerance.
     *
     * Default: `1`.
     */
    opttolerance?: number;


    /* ------------------------------- Sizing ------------------------------- */

    /**
     * Minimum image size used during preprocessing.
     */
    minSize?: number;

    /**
     * Maximum image size used during preprocessing.
     */
    maxSize?: number;

    /**
     * Additional scaling factor.
     *
     * Default: `1`.
     */
    scale?: number;


    /* ------------------------------- Filters ------------------------------ */

    /**
     * Brightness adjustment.
     *
     * Default: `1`.
     */
    brightness?: number;

    /**
     * Contrast adjustment.
     *
     * Default: `1`.
     */
    contrast?: number;

    /**
     * Invert the image.
     *
     * Default: `0`.
     */
    invert?: number;

    /**
     * Blur amount.
     *
     * Default: `0`.
     */
    blur?: number;


    /* ---------------------------- SVG processing -------------------------- */

    /**
     * Crop output to the image boundaries.
     *
     * Default: `true`.
     */
    crop?: boolean;

    /**
     * Optimize SVG path data.
     *
     * Default: `true`.
     */
    optimize?: boolean;

    /**
     * Minify the generated `d` attribute.
     */
    minifyD?: boolean;

    /**
     * Add `width` and `height` attributes to the SVG.
     *
     * Default: `true`.
     */
    addDimensions?: boolean;

    /**
     * Convert path commands to relative commands.
     *
     * Default: `true`.
     */
    toRelative?: boolean;

    /**
     * Convert compatible commands to SVG shorthand commands.
     *
     * Default: `true`.
     */
    toShorthands?: boolean;

    /**
     * Number of decimal places in generated coordinates.
     *
     * Default: `3`.
     */
    decimals?: number;


    /* ----------------------------- Extra output --------------------------- */

    /**
     * Generate the unoptimized polygon representation.
     *
     * Default: `true`.
     */
    getPolygon?: boolean;

    /**
     * Enable Web Worker processing.
     */
    useWorker?: boolean;
}


/* ========================================================================== */
/*                             RESULT INTERFACE                               */
/* ========================================================================== */

/**
 * Result generated by Potrace Plus.
 */
interface PotracePlusResult {

    /**
     * Complete SVG markup using a compound path.
     */
    svg: string;

    /**
     * SVG markup with paths split into separate elements.
     */
    svgSplit: string;

    /**
     * Complete SVG `d` attribute.
     */
    d: string;

    /**
     * Individual `d` strings for split paths.
     */
    dArr: string[];

    /**
     * Width of the generated tracing.
     */
    width: number;

    /**
     * Height of the generated tracing.
     */
    height: number;

    /**
     * Number of path commands.
     */
    commands: number;

    /**
     * Optimized SVG path data.
     */
    pathData: PotracePathData;

    /**
     * Normalized path data separated into individual contours.
     */
    pathDataArr: PotracePathDataArray;

    /**
     * Bounding box of the processed image/path.
     */
    bb: PotraceBoundingBox;

    /**
     * Processed image width.
     */
    w: number;

    /**
     * Processed image height.
     */
    h: number;

    /**
     * Internal scale adjustment.
     */
    scaleAdjust: number;

    /**
     * Unoptimized polygon representation.
     */
    polygons: PotracePolygonArray;

    /**
     * Return the SVG representation.
     *
     * @param split
     * `false` returns the compound SVG.
     * `true` returns the split SVG.
     *
     * Default: `false`.
     */
    getSVG(split?: boolean): string;

    /**
     * Return SVG path data suitable for a `d` attribute.
     */
    getD(): string;

    /**
     * Return path data.
     */
    getPathData(): PotracePathData;

    /**
     * Return normalized path data.
     */
    getPathDataNorm(): PotracePathData;

    /**
     * Generate a PDF and return its browser Object URL.
     */
    getPdf(): string;
}


/* ========================================================================== */
/*                           POTRACE PLUS INSTANCE                            */
/* ========================================================================== */

/**
 * An instance created with `new PotracePlus(...)`.
 *
 * The constructor form is useful when the library is being used
 * as a Potrace object rather than directly through the asynchronous
 * helper function.
 */
interface PotracePlusInstance {

    /**
     * Input image used by the instance.
     */
    image?: unknown;

    /**
     * Potrace Plus configuration.
     */
    options?: PotracePlusOptions;

    /**
     * SVG result, when tracing has completed.
     */
    svg?: string;

    /**
     * Split SVG result.
     */
    svgSplit?: string;

    /**
     * Path-data string.
     */
    d?: string;

    /**
     * Split path-data strings.
     */
    dArr?: string[];

    /**
     * Width of the resulting image.
     */
    width?: number;

    /**
     * Height of the resulting image.
     */
    height?: number;

    /**
     * Number of generated commands.
     */
    commands?: number;

    /**
     * Optimized path data.
     */
    pathData?: PotracePathData;

    /**
     * Normalized path data.
     */
    pathDataArr?: PotracePathDataArray;

    /**
     * Return the generated SVG.
     */
    getSVG(split?: boolean): string;

    /**
     * Return the generated path `d` attribute.
     */
    getD(): string;

    /**
     * Return path data.
     */
    getPathData(): PotracePathData;

    /**
     * Return normalized path data.
     */
    getPathDataNorm(): PotracePathData;

    /**
     * Generate a PDF and return its Object URL.
     */
    getPdf(): string;
}


/* ========================================================================== */
/*                         CONSTRUCTOR SIGNATURE                              */
/* ========================================================================== */

/**
 * Potrace Plus constructor.
 *
 * Allows:
 *
 *     const traced = new PotracePlus(image);
 *
 * or:
 *
 *     const traced = new PotracePlus(image, options);
 */
interface PotracePlusConstructor {

    /**
     * Create a Potrace Plus instance.
     */
    new (
        input:
            | HTMLImageElement
            | HTMLCanvasElement
            | SVGElement
            | Blob
            | File
            | string,
        options?: PotracePlusOptions
    ): PotracePlusInstance;

    /**
     * Invoke Potrace Plus directly.
     *
     * Example:
     *
     *     const traced = await PotracePlus(image);
     */
    (
        input:
            | HTMLImageElement
            | HTMLCanvasElement
            | SVGElement
            | Blob
            | File
            | string,
        options?: PotracePlusOptions
    ): Promise<PotracePlusResult>;
}


/* ========================================================================== */
/*                              GLOBAL FUNCTION                               */
/* ========================================================================== */

/**
 * Global Potrace Plus API.
 *
 * This value is supplied by `potrace-plus.min.js`.
 */
declare const PotracePlus: PotracePlusConstructor;


/* ========================================================================== */
/*                                  WINDOW                                    */
/* ========================================================================== */

/**
 * Potrace Plus exposed on the browser window.
 */
interface Window {

    /**
     * Global Potrace Plus constructor/function.
     */
    PotracePlus: PotracePlusConstructor;
}
